"""Pose Logger & Data Storage — structured JSON and CSV dataset exporter.

Generates:
- ``pose_results.json``
- ``pose_statistics.csv``
- ``pose_quality_report.md``
"""

from __future__ import annotations

import csv
import json
import os
from typing import Any

from src.core.models.pose_result import PoseResult


class PoseLogger:
    """Logs and exports PoseResult objects to JSON, CSV, and markdown quality reports."""

    def __init__(self) -> None:
        self._poses: list[PoseResult] = []

    def log_pose(self, pose: PoseResult) -> None:
        """Store a PoseResult instance for export."""
        self._poses.append(pose)

    def log_poses(self, poses: list[PoseResult]) -> None:
        """Store multiple PoseResult instances for export."""
        for p in poses:
            self.log_pose(p)

    def export_json(self, output_path: str) -> None:
        """Export all logged poses to pose_results.json."""
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

        pose_dicts = [self._pose_to_dict(p) for p in self._poses]

        avg_conf = (
            sum(p.overall_confidence for p in self._poses) / max(1, len(self._poses))
        )
        avg_time = (
            sum(p.processing_time_ms for p in self._poses) / max(1, len(self._poses))
        )

        payload = {
            "poses": pose_dicts,
            "summary": {
                "total_pose_samples": len(self._poses),
                "average_overall_confidence": round(avg_conf, 4),
                "average_processing_time_ms": round(avg_time, 2),
                "backends_used": list(set(p.backend_name for p in self._poses)),
            },
        }

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, default=str)

    def export_csv(self, output_path: str) -> None:
        """Export all logged poses to pose_statistics.csv."""
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

        fieldnames = [
            "sample_id",
            "roi_id",
            "interaction_id",
            "frame_index",
            "timestamp",
            "track_id",
            "backend_name",
            "topology",
            "num_keypoints",
            "overall_confidence",
            "quality_score",
            "processing_time_ms",
        ]

        with open(output_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()

            for p in self._poses:
                writer.writerow(
                    {
                        "sample_id": p.sample_id,
                        "roi_id": p.roi_id,
                        "interaction_id": p.interaction_id,
                        "frame_index": p.frame_index,
                        "timestamp": p.timestamp,
                        "track_id": p.track_id,
                        "backend_name": p.backend_name,
                        "topology": p.topology,
                        "num_keypoints": p.num_keypoints,
                        "overall_confidence": p.overall_confidence,
                        "quality_score": p.quality_score,
                        "processing_time_ms": p.processing_time_ms,
                    }
                )

    def export_quality_report(self, output_path: str) -> None:
        """Generate formatted pose_quality_report.md."""
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

        avg_conf = (
            sum(p.overall_confidence for p in self._poses) / max(1, len(self._poses))
        )
        avg_time = (
            sum(p.processing_time_ms for p in self._poses) / max(1, len(self._poses))
        )
        avg_qual = (
            sum(p.quality_score for p in self._poses) / max(1, len(self._poses))
        )

        lines: list[str] = []
        lines.append("# Pose Estimation Abstraction Layer — Research Report\n")
        lines.append(f"**Total Pose Samples Extracted:** {len(self._poses)}")
        lines.append(f"**Average Keypoint Confidence:** {avg_conf:.0%}")
        lines.append(f"**Average Pose Quality Score:** {avg_qual:.2f}")
        lines.append(f"**Average Backend Inference Time:** {avg_time:.2f} ms/frame\n")

        lines.append("## Pose Sample Summary\n")
        lines.append("| Sample ID | Frame | Track ID | Backend | Confidence | Quality Score | Inference Time (ms) |")
        lines.append("|---|---|---|---|---|---|---|")

        for p in self._poses[:20]:  # Show top 20 sample rows
            lines.append(
                f"| {p.sample_id} | {p.frame_index} | {p.track_id} | "
                f"{p.backend_name} | {p.overall_confidence:.0%} | {p.quality_score:.2f} | {p.processing_time_ms:.1f}ms |"
            )

        lines.append("\n---\n*Report generated by the Pose Estimation Abstraction Layer.*\n")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    def export_all(
        self,
        json_path: str,
        csv_path: str,
        report_path: str,
    ) -> None:
        """Export JSON, CSV, and markdown quality report."""
        self.export_json(json_path)
        self.export_csv(csv_path)
        self.export_quality_report(report_path)

    def get_poses(self) -> list[PoseResult]:
        """Return all logged poses."""
        return list(self._poses)

    def get_pose_results(self) -> list[PoseResult]:
        """Return all logged poses (alias for get_poses)."""
        return self.get_poses()

    def clear(self) -> None:
        """Clear internal pose log storage."""
        self._poses.clear()

    @staticmethod
    def _pose_to_dict(pose: PoseResult) -> dict[str, Any]:
        """Serialise a PoseResult instance to a clean dictionary."""
        return {
            "sample_id": pose.sample_id,
            "roi_id": pose.roi_id,
            "interaction_id": pose.interaction_id,
            "frame_index": pose.frame_index,
            "timestamp": pose.timestamp,
            "track_id": pose.track_id,
            "keypoints_pixel": [list(kp) for kp in pose.keypoints_pixel],
            "keypoints_normalized": [list(kp) for kp in pose.keypoints_normalized],
            "num_keypoints": pose.num_keypoints,
            "topology": pose.topology,
            "overall_confidence": pose.overall_confidence,
            "quality_score": pose.quality_score,
            "bbox_reference": list(pose.bbox_reference),
            "backend_name": pose.backend_name,
            "processing_time_ms": pose.processing_time_ms,
            "metadata": pose.metadata,
        }
